language: python
 
python:
  - "3.4"
 
branches:
  only:
    - master
 
install: "pip install -r requirements.txt"

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database mydb;' -U postgres
 
script: "bash travis.bash"
